name: base
channels:
  - conda-forge
  - defaults
  - main
dependencies:
  # Environment specific dependencies
  - python=3.9
  - numpy
  - pandas
  - shapely
  - rtree
  - geopandas
  - matplotlib
  - descartes
  - tqdm
  - stringcase
  - pyarrow
  - isort
  - black
  - pytest
  - ipykernel